dist: bionic
languages:
  - cpp
  - python
python:
  - "3.7"
cache: pip
compiler:
  - gcc 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - python
before_script:
  - sudo apt update && sudo apt install python3.7
  - python3 --version
  - pip install -U pip
  - pip install pathlib


jobs:
    include:
        - stage: build
          script:
            - export CC=gcc-7
            - export CXX=g++-7
            - cd cmake/build/ && python ../make_project.py -target "mac"
            - cmake .  -DCMAKE_SYSTEM_NAME="Linux" -DBUILD_TYPE="Release" 
            - make 
        
        - stage: unittests
          script: for TEST in $(ls *unittest); do ./$TEST; done; 
