dist: bionic
languages:
  - cpp
  - python
cache: pip
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - python
script:
  - python3 --version
  - pip3 install -U pip
  - pip3 install pathlib
  # Link gcc-6 and g++-6 to their standard commands
  #- ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  #- ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - pip install --user -U pip
  - pip install --user pathlib
  - export CC=/usr/bin/clang
  - export CXX=/usr/bin/clang++
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cd cmake/build/ && python ../make_project.py -target "linux" && cmake -DCMAKE_SYSTEM_NAME="Linux" . && make
