dist: bionic
languages:
  - cpp
  - python
python:
  - "3.7"
cache: pip
compiler:
  - gcc 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake
      - python
before_script:
  - sudo apt update && sudo apt install python3.7
  - python3 --version
  - pip install -U pip
  - pip install pathlib


script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cd cmake/build/ && python3 ../make_project.py -target "mac"
  - cmake .  -DCMAKE_SYSTEM_NAME="Linux" -DBUILD_TYPE="Release" 
  - make
  - for TEST in $(ls *unittest); do ./$TEST; done;
   
